config/routes.rb
Liverailsapp::Application.routes.draw do
  resources :rooms
  root :to=>'rooms#index'
  delete '/logout', :to=>'sessions#destroy'
  get 'subscribe/:channel_name', :to=>'subscriptions#subscribe'
  get '/auth/:provider/callback', :to=>"sessions#create"
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(fb_params)
    info = fb_params[:info]
    puts info.inspect
    u = self.where(:fb_id=>fb_params[:uid]).first_or_initialize
    if(u.new_record?)
      u.fb_id=fb_params[:uid]
      u.name=info[:name]
      u.email=info[:email]
      u.provider_properties = info.slice(:nickname, :image, :location)
      u.save!
    end
    u
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user = User.where(:id=>session[:current_user_id]).first
  end
  def authenticate
    unless(current_user)
      redirect_to '/auth/facebook'
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # find out if people join the room
  # handle posting new chats
  # broadcast chat message on reception to everybody
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate, :except=>[:index]
  def index
    @rooms = Room.all
  end
  def new
    @room = Room.new
  end
  def create
    @room=Room.create(params.require(:room).permit(:name))
    if(@room.save)
      redirect_to root_path
    else
      render :new
    end
  end
  def show
    @room = Room.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:current_user_id] = User.from_omniauth(request.env['omniauth.auth']).id
    redirect_to root_path
  end
  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/subscriptions_controller.rb
require 'redis_utils'
class SubscriptionsController < ApplicationController
  include ActionController::Live
  def subscribe
    begin
      channel_name = params[:channel_name]
      response.headers['Content-Type']='text/event-stream'
      redis = RedisUtils.instance.redis_client
      redis.subscribe channel_name do |on|
        on.message do |channel,message|
          response.stream.write("data: " + message + "\n\n")
        end
      end
    rescue IOError
      puts "rescued from io error"
    ensure
      response.stream.close
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user = User.where(:id=>session[:current_user_id]).first
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Liverailsapp</title>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"%>
  <%= csrf_meta_tags %>
  <%= yield :js_head %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Live Rails App</h1>
    </div>
    <div class="col-md-6">
      <% if current_user %>
        <p>Logged in as <%=@current_user.name%></p>
      <%= link_to 'Logout', logout_path, :method=>:delete %>
    <% else %>
        <%= link_to 'Login', '/auth/facebook' %>
    <% end %>
    </div>
  </div>
  <div class="row">
  <%= yield %>
  </div>

  </div>
  </body>
</html>

app/views/rooms/_room.html.erb
<li><%=room.name%></li>

app/views/rooms/index.html.erb
<div class='col-md-12'>
<h2>Displaying Rooms</h2>
<% if current_user %>
  <ul>
  <%= render @rooms %>
</ul>
<%= link_to 'New Room', new_room_path %>
<% end %>
</div>

app/views/rooms/new.html.erb
<div class='col-md-12'>
<%=simple_form_for @room do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/rooms/show.html.erb
<% content_for :js_head do %>
  <script type="text/javascript">
    window.room_name = "<%=@room.name%>";
  </script>
<% end %>
<div class='col-md-8'>
  <div class="chat-screen">
    <p> Chat text goes here</p>
  </div>
  <div class="chat-input">
    <%= text_field_tag :chat_text %>
  </div>
</div>
<div class='col-md-4'>
  <div class="participants">
    <ul>
      <li>Some</li>
      <li>randome</li>
      <li>people</li>
      <li>Some</li>
    </ul>
  </div>
</div>